#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.PP1.BL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDPedidos")]
	public partial class BDClientesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    #endregion
		
		public BDClientesDataContext() : 
				base(global::UPC.PP1.BL.Properties.Settings.Default.BDPedidosConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public BDClientesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDClientesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDClientesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDClientesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_cliente;
		
		private string _tipo_doc;
		
		private string _nu_doc;
		
		private string _tx_nombres;
		
		private string _email;
		
		private string _nu_telefono;
		
		private string _tx_direccion;
		
		private System.Nullable<System.DateTime> _fec_creacion;
		
		private System.Nullable<System.DateTime> _fec_actualizacion;
		
		private string _tx_estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_clienteChanging(int value);
    partial void Onid_clienteChanged();
    partial void Ontipo_docChanging(string value);
    partial void Ontipo_docChanged();
    partial void Onnu_docChanging(string value);
    partial void Onnu_docChanged();
    partial void Ontx_nombresChanging(string value);
    partial void Ontx_nombresChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onnu_telefonoChanging(string value);
    partial void Onnu_telefonoChanged();
    partial void Ontx_direccionChanging(string value);
    partial void Ontx_direccionChanged();
    partial void Onfec_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_creacionChanged();
    partial void Onfec_actualizacionChanging(System.Nullable<System.DateTime> value);
    partial void Onfec_actualizacionChanged();
    partial void Ontx_estadoChanging(string value);
    partial void Ontx_estadoChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_cliente
		{
			get
			{
				return this._id_cliente;
			}
			set
			{
				if ((this._id_cliente != value))
				{
					this.Onid_clienteChanging(value);
					this.SendPropertyChanging();
					this._id_cliente = value;
					this.SendPropertyChanged("id_cliente");
					this.Onid_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_doc", DbType="NChar(10)")]
		public string tipo_doc
		{
			get
			{
				return this._tipo_doc;
			}
			set
			{
				if ((this._tipo_doc != value))
				{
					this.Ontipo_docChanging(value);
					this.SendPropertyChanging();
					this._tipo_doc = value;
					this.SendPropertyChanged("tipo_doc");
					this.Ontipo_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_doc", DbType="NVarChar(14)")]
		public string nu_doc
		{
			get
			{
				return this._nu_doc;
			}
			set
			{
				if ((this._nu_doc != value))
				{
					this.Onnu_docChanging(value);
					this.SendPropertyChanging();
					this._nu_doc = value;
					this.SendPropertyChanged("nu_doc");
					this.Onnu_docChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_nombres", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tx_nombres
		{
			get
			{
				return this._tx_nombres;
			}
			set
			{
				if ((this._tx_nombres != value))
				{
					this.Ontx_nombresChanging(value);
					this.SendPropertyChanging();
					this._tx_nombres = value;
					this.SendPropertyChanged("tx_nombres");
					this.Ontx_nombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_telefono", DbType="NVarChar(50)")]
		public string nu_telefono
		{
			get
			{
				return this._nu_telefono;
			}
			set
			{
				if ((this._nu_telefono != value))
				{
					this.Onnu_telefonoChanging(value);
					this.SendPropertyChanging();
					this._nu_telefono = value;
					this.SendPropertyChanged("nu_telefono");
					this.Onnu_telefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_direccion", DbType="NVarChar(100)")]
		public string tx_direccion
		{
			get
			{
				return this._tx_direccion;
			}
			set
			{
				if ((this._tx_direccion != value))
				{
					this.Ontx_direccionChanging(value);
					this.SendPropertyChanging();
					this._tx_direccion = value;
					this.SendPropertyChanged("tx_direccion");
					this.Ontx_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_creacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fec_creacion
		{
			get
			{
				return this._fec_creacion;
			}
			set
			{
				if ((this._fec_creacion != value))
				{
					this.Onfec_creacionChanging(value);
					this.SendPropertyChanging();
					this._fec_creacion = value;
					this.SendPropertyChanged("fec_creacion");
					this.Onfec_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_actualizacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> fec_actualizacion
		{
			get
			{
				return this._fec_actualizacion;
			}
			set
			{
				if ((this._fec_actualizacion != value))
				{
					this.Onfec_actualizacionChanging(value);
					this.SendPropertyChanging();
					this._fec_actualizacion = value;
					this.SendPropertyChanged("fec_actualizacion");
					this.Onfec_actualizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_estado", DbType="NVarChar(10)")]
		public string tx_estado
		{
			get
			{
				return this._tx_estado;
			}
			set
			{
				if ((this._tx_estado != value))
				{
					this.Ontx_estadoChanging(value);
					this.SendPropertyChanging();
					this._tx_estado = value;
					this.SendPropertyChanged("tx_estado");
					this.Ontx_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
