#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.PP1.BL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDPedidos")]
	public partial class BDPedidosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    #endregion
		
		public BDPedidosDataContext() : 
				base(global::UPC.PP1.BL.Properties.Settings.Default.BDPedidosConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDPedidosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDPedidosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDPedidosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDPedidosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Clientes
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Pedido> Pedidos
		{
			get
			{
				return this.GetTable<Pedido>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Productos
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nu_dni;
		
		private string _tx_nombre;
		
		private string _tx_estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnu_dniChanging(int value);
    partial void Onnu_dniChanged();
    partial void Ontx_nombreChanging(string value);
    partial void Ontx_nombreChanged();
    partial void Ontx_estadoChanging(string value);
    partial void Ontx_estadoChanged();
    #endregion
		
		public Cliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_dni", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nu_dni
		{
			get
			{
				return this._nu_dni;
			}
			set
			{
				if ((this._nu_dni != value))
				{
					this.Onnu_dniChanging(value);
					this.SendPropertyChanging();
					this._nu_dni = value;
					this.SendPropertyChanged("nu_dni");
					this.Onnu_dniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_nombre", DbType="NVarChar(50)")]
		public string tx_nombre
		{
			get
			{
				return this._tx_nombre;
			}
			set
			{
				if ((this._tx_nombre != value))
				{
					this.Ontx_nombreChanging(value);
					this.SendPropertyChanging();
					this._tx_nombre = value;
					this.SendPropertyChanged("tx_nombre");
					this.Ontx_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_estado", DbType="NVarChar(1)")]
		public string tx_estado
		{
			get
			{
				return this._tx_estado;
			}
			set
			{
				if ((this._tx_estado != value))
				{
					this.Ontx_estadoChanging(value);
					this.SendPropertyChanging();
					this._tx_estado = value;
					this.SendPropertyChanged("tx_estado");
					this.Ontx_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pedidos")]
	public partial class Pedido
	{
		
		private System.Nullable<int> _nu_cod_pedido;
		
		private System.Nullable<int> _nu_cod_cliente;
		
		private System.Nullable<int> _nu_cod_producto;
		
		private string _tx_desc_pedido;
		
		private System.Nullable<System.DateTime> _fec_fec_pedido;
		
		private string _tx_estado_pedido;
		
		public Pedido()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_cod_pedido", DbType="Int")]
		public System.Nullable<int> nu_cod_pedido
		{
			get
			{
				return this._nu_cod_pedido;
			}
			set
			{
				if ((this._nu_cod_pedido != value))
				{
					this._nu_cod_pedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_cod_cliente", DbType="Int")]
		public System.Nullable<int> nu_cod_cliente
		{
			get
			{
				return this._nu_cod_cliente;
			}
			set
			{
				if ((this._nu_cod_cliente != value))
				{
					this._nu_cod_cliente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_cod_producto", DbType="Int")]
		public System.Nullable<int> nu_cod_producto
		{
			get
			{
				return this._nu_cod_producto;
			}
			set
			{
				if ((this._nu_cod_producto != value))
				{
					this._nu_cod_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_desc_pedido", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string tx_desc_pedido
		{
			get
			{
				return this._tx_desc_pedido;
			}
			set
			{
				if ((this._tx_desc_pedido != value))
				{
					this._tx_desc_pedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fec_fec_pedido", DbType="Date")]
		public System.Nullable<System.DateTime> fec_fec_pedido
		{
			get
			{
				return this._fec_fec_pedido;
			}
			set
			{
				if ((this._fec_fec_pedido != value))
				{
					this._fec_fec_pedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_estado_pedido", DbType="NVarChar(50)")]
		public string tx_estado_pedido
		{
			get
			{
				return this._tx_estado_pedido;
			}
			set
			{
				if ((this._tx_estado_pedido != value))
				{
					this._tx_estado_pedido = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nu_cod;
		
		private string _tx_nom_producto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnu_codChanging(int value);
    partial void Onnu_codChanged();
    partial void Ontx_nom_productoChanging(string value);
    partial void Ontx_nom_productoChanged();
    #endregion
		
		public Producto()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nu_cod", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int nu_cod
		{
			get
			{
				return this._nu_cod;
			}
			set
			{
				if ((this._nu_cod != value))
				{
					this.Onnu_codChanging(value);
					this.SendPropertyChanging();
					this._nu_cod = value;
					this.SendPropertyChanged("nu_cod");
					this.Onnu_codChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tx_nom_producto", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string tx_nom_producto
		{
			get
			{
				return this._tx_nom_producto;
			}
			set
			{
				if ((this._tx_nom_producto != value))
				{
					this.Ontx_nom_productoChanging(value);
					this.SendPropertyChanging();
					this._tx_nom_producto = value;
					this.SendPropertyChanged("tx_nom_producto");
					this.Ontx_nom_productoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
